---
name: "Docker MRTG"
version: "v2.5.7"
slug: "ffb-dckr-mrtg"
description: "Dockerized MRTG Graph Generator for SNMP Monitoring"
startup: services
boot: auto
init: false
host_network: true
homeassistant_api: false
url: https://github.com/fboaventura/dckr-mrtg
ports:
  - 80/tcp:8082
ports_description:
  - 80: Web interface for MRTG
map:
  - data: /mrtg
  - addon_config: /etc/mrtg/conf.d
options:
  -
schema: {}
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
image: "fboaventura/dckr-mrtg"
