---
services:
  mrtg:
    build: .
    image: dckr-mrtg:2.5.7
    container_name: mrtg
    hostname: mrtg
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/mrtg/html"
    environment:
      TZ: "Brazil/East"
      HOSTS: "public:192.168.0.123"
      USERID: 100
      GROUPID: 101
      REGENERATEHTML: "yes"
      INDEXMAKEROPTIONS: ""
      MRTG_COLUMNS: 2
    tmpfs:
      - "/run"
