var.basedir  = "/mrtg"
var.logdir   = "/var/log/lighttpd"
var.statedir = "/var/lib/lighttpd"
server.modules += (
    "mod_access",
    "mod_alias",
    "mod_accesslog",
    "mod_cgi",
    "mod_compress",
    "mod_setenv"
)
server.username      = "lighttpd"
server.groupname     = "lighttpd"
server.document-root = var.basedir + "/html"
server.pid-file      = "/run/lighttpd.pid"
server.indexfiles    = ("index.php", "index.html",
                        "index.htm", "default.htm")
server.follow-symlink  = "disable"
dir-listing.activate   = "disable"
static-file.exclude-extensions = (".php", ".pl", ".cgi", ".fcgi")

setenv.add-response-header = (
    "X-Frame-Options"        => "SAMEORIGIN",
    "X-Content-Type-Options" => "nosniff",
    "Content-Security-Policy" => "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline';"
)

# Access Logs
accesslog.format = "%h %V %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""

url.access-deny = ("~", ".inc")
alias.url = (
    "/cgi-bin/" =>  "/mrtg/cgi-bin/"
)
$HTTP["url"] =~ "^/cgi-bin/" {
    # only allow cgi's in this directory
    cgi.assign = (
          ".pl"   =>      "/usr/bin/perl",
          ".cgi"  =>      "/usr/bin/perl"
        )
}
